version: '3'
services:
  proxy:
    image: haproxy:latest
    container_name: proxy
    ports:
      - "8080:80"
    volumes:
      - ./proxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8081:8080"
