version: '3.8'
services:
  proxy:
    image: caddy:latest
    container_name: caddy_proxy_apache-http-server # Name matches hyphenated style
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - ./proxy-configs/caddy-apache-http-server.caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      - caddy_apache_http_server_net

  backend:
    image: httpd:latest
    container_name: apache-http-server_webserver_latest # Name matches hyphenated style
    ports:
      - "8081:80"
    networks:
      - caddy_apache_http_server_net

networks:
  caddy_apache_http_server_net:
    driver: bridge
