version: '3.8'
services:
  proxy:
    image: caddy:latest
    container_name: caddy_proxy_caddy
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - ./proxy-configs/caddy-caddy.caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      - caddy_caddy_net

  backend:
    image: caddy:latest
    container_name: caddy_webserver_latest
    ports:
      - "8081:80"
    networks:
      - caddy_caddy_net

networks:
  caddy_caddy_net:
    driver: bridge
