version: '3.8'
services:
  proxy:
    image: haproxy:latest
    container_name: haproxy_proxy_openlitespeed
    ports:
      - "8080:80" # HAProxy listens on 80 internally, exposed on host 8080
    depends_on:
      - backend
    volumes:
      - ./proxy-configs/haproxy-openlitespeed.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - haproxy_ols_net

  backend:
    image: litespeedtech/openlitespeed:latest # Official OpenLiteSpeed image
    container_name: openlitespeed_webserver_latest
    ports:
      - "8081:8088" # OLS listens on 8088 internally, exposed on host 8081
    networks:
      - haproxy_ols_net

networks:
  haproxy_ols_net:
    driver: bridge
