version: '3.8'
services:
  proxy:
    image: haproxy:latest
    container_name: haproxy_proxy_jetty
    ports:
      - "8080:80" # HAProxy listens on 80 internally, exposed on host 8080
    depends_on:
      - backend
    volumes:
      - ./proxy-configs/haproxy-jetty.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - haproxy_jetty_net

  backend:
    image: jetty:latest # Official Jetty image
    container_name: jetty_webserver_latest
    ports:
      - "8081:8080" # Jetty listens on 8080 internally, exposed on host 8081
    networks:
      - haproxy_jetty_net

networks:
  haproxy_jetty_net:
    driver: bridge
