version: '3.8'
services:
  proxy:
    image: nginx:latest
    container_name: nginx_proxy_caddy
    ports:
      - "8080:80" # Nginx (proxy) listens on 80 internally, exposed on host 8080
    depends_on:
      - backend
    volumes:
      - ./proxy-configs/nginx-caddy.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - nginx_caddy_net

  backend:
    image: caddy:latest # Official Caddy image
    container_name: caddy_webserver_latest
    ports:
      - "8081:80" # Caddy listens on 80 internally, exposed on host 8081
    networks:
      - nginx_caddy_net

networks:
  nginx_caddy_net:
    driver: bridge
