version: '3.8'
services:
  proxy:
    image: varnish:latest
    container_name: varnish_proxy_caddy
    ports:
      - "8080:80" # Varnish listens on 80 internally, exposed on host 8080
    depends_on:
      - backend
    volumes:
      # FIX: Correct VCL filename and standard mount path
      - ./proxy-configs/varnish-caddy.vcl:/etc/varnish/default.vcl:ro
    command: ["varnishd", "-F", "-f", "/etc/varnish/default.vcl", "-s", "malloc,256m"] # Command to load VCL
    networks:
      - varnish_caddy_net

  backend:
    image: caddy:latest
    container_name: caddy_webserver_latest
    ports:
      - "8081:80" # Caddy listens on 80 internally, exposed on host 8081
    networks:
      - varnish_caddy_net

networks:
  varnish_caddy_net:
    driver: bridge
