version: '3.8'
services:
  proxy:
    image: varnish:latest
    container_name: varnish_proxy_nodejs
    ports:
      - "8080:80" # Varnish listens on 80 internally, exposed on host 8080
    depends_on:
      - backend
    volumes:
      # FIX: Correct VCL filename and standard mount path
      - ./proxy-configs/varnish-nodejs.vcl:/etc/varnish/default.vcl:ro
    command: ["varnishd", "-F", "-f", "/etc/varnish/default.vcl", "-s", "malloc,256m"] # Command to load VCL
    networks:
      - varnish_nodejs_net

  backend:
    build: ../backend # Path to backend folder from the docker-compose file
    image: nodejs_custom_latest_build
    container_name: nodejs_webserver_latest
    ports:
      - "8081:3000" # Node.js listens on 3000 internally, exposed on host 8081
    networks:
      - varnish_nodejs_net

networks:
  varnish_nodejs_net:
    driver: bridge
