version: '3.8'
services:
  proxy:
    image: varnish:latest
    container_name: varnish_proxy_nginx
    ports:
      - "8080:80" # Varnish listens on 80 internally, exposed on host 8080
    depends_on:
      - backend
    volumes:
      # Correct VCL filename and standard mount path
      - ./proxy-configs/varnish-nginx.vcl:/etc/varnish/default.vcl:ro
    command: ["varnishd", "-F", "-f", "/etc/varnish/default.vcl", "-s", "malloc,256m"] # Command to load VCL
    networks:
      - varnish_nginx_net

  backend:
    image: nginx:latest # Official Nginx image
    container_name: nginx_webserver_latest
    ports:
      - "8081:80" # Nginx listens on 80 internally, exposed on host 8081
    networks:
      - varnish_nginx_net

networks:
  varnish_nginx_net:
    driver: bridge
